### ISSUE TITLE
[question] It's a really gem! :)

### ISSUE THREAD

**Issue by serhii-budnik** [andriy-baran/rspec_database_helper#1]
Hello Andriy :) Your gem is really good. Do you have a goal to implement additional functionality for other methods like build, build_stubbed?

**Comment by andriy-baran** [comment]
Hi Sergii (@Zikot4),
I haven't yet. But it sounds as a good idea. If you can show how do you plan to use it we can create a ticket for that

**Comment by andriy-baran** [comment]
Hi @Zikot4 
I don't plan to do this, because intention of this gem is to create records in test database. 
For `build` and `build_stubbed` you can use another gem I made [rspec_vars_helper](https://github.com/andriy-baran/rspec_vars_helper)
 ```ruby
RSpec.describe 'Subject' do
   vars do
     mispick_report { build(:mispick_report) }
   end
end
```
