### ISSUE TITLE
<module:ClassMethods>': uninitialized constant Parser::TreeRewriter (NameError)

### ISSUE THREAD

**Issue by orest-kostiuk** [andriy-baran/rspec_database_helper#2]
Hi, after installed gem I get this error 

/Users/orestkostiuk/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec_database_helper-0.1.0/lib/rspec_database_helper.rb:7:in `<module:ClassMethods>': uninitialized constant Parser::TreeRewriter (NameError)

**Comment by andriy-baran** [comment]
Hi @Ckazo4nik this issue is caused by `parser` gem. Class `Parser::Rewriter` is deprecated by `Parser::TreeRewriter` so probably on your system it does not exists.
